name: build-release

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: checkout submodules
      run: git submodule update --init
          
    - name: configure cmake build
      run: mkdir -p cmake/build && cd cmake/build && cmake ../.. -G "Visual Studio 17 2022"

    - name: make
      run: cmake --build .\ --config Release

    - name: create zip archive
      run: 7z a grpc-release.zip .\Release\*

    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './release.zip'
          release-tag: SNAPSHOT 
          repo-token: ${{ secrets.GITHUB_TOKEN }}    

