name: build-release

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    permissions:
      issues: write

    steps:
    - uses: actions/checkout@v3

    #- name: checkout submodules
    #  run: git submodule update --init
          
    #- name: configure cmake build
    #  run: mkdir -p cmake/build && cd cmake/build && cmake ../.. -G "Visual Studio 17 2022"

    #- name: make
    #  run: cd cmake/build && cmake --build .\ --config Release

    #- name: create zip archive
    #  run: cd cmake/build && 7z a grpc-release.zip .\Release\* && mv grpc-release.zip grpc-release-SNAPSHOT-$(date +"%Y-%m-%d_%H-%M-%S").zip

    - name: fake build files
      run: mkdir -p cmake/build && touch cmake/build/grpc-release-SNAPSHOT-123.zip
      
    - name: list
      run: ls && echo "---" && ls cmake/build/

    - uses: actions/upload-artifact@v3
      with: 
        name: my-artifact  
        path: 'cmake/build/grpc-release-SNAPSHOT-*.zip'
        
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: 'cmake/build/grpc-release-SNAPSHOT-*.zip'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}    

