name: build-release

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    permissions:
      issues: write

    steps:
    - uses: actions/checkout@v3

    #- name: checkout submodules
    #  run: git submodule update --init
          
    #- name: configure cmake build
    #  run: mkdir -p cmake/build && cd cmake/build && cmake ../.. -G "Visual Studio 17 2022"

    #- name: make
    #  run: cd cmake/build && cmake --build .\ --config Release

    #- name: create zip archive
    #  run: cd cmake/build && 7z a grpc-release.zip .\Release\* && mv grpc-release.zip grpc-release-SNAPSHOT-$(date +"%Y-%m-%d_%H-%M-%S").zip

    - name: fake build files
      run: mkdir -p cmake/build && touch cmake/build/grpc-release-SNAPSHOT-123.zip
      
    - name: list
      run: ls && echo "---" && ls cmake/build/

    - name: Get release by name (Windows)
      id: getrelease-windows
      run: |
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/tags/$env:RELEASE_NAME" -Headers @{Authorization="Bearer $env:GITHUB_TOKEN"}
        echo "::set-output name=url::$($release.upload_url)"
      env:
        RELEASE_NAME: 'SNAPSHOT' # Replace with your release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Upload Zip to Release (Windows)
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        asset_path: cmake/build/grpc-release-SNAPSHOT-123.zip
        asset_name: grpc-release-SNAPSHOT-123.zip
        asset_content_type: application/zip
        upload_url: ${{ steps.getrelease-windows.outputs.url }}

