name: build-release

on: [push]

jobs:
  build:

    runs-on: windows-2022

    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: checkout submodules
      run: git submodule update --init
          
    - name: configure cmake build
      run: mkdir -p cmake/build && cd cmake/build && cmake ../.. -G "Visual Studio 17 2022"

    - name: make
      run: cd cmake/build && cmake --build .\ --config Release

    - name: create zip archive
      run: cd cmake/build && 7z a grpc-release.zip .\Release\* && mv grpc-release.zip grpc-release-SNAPSHOT-$(date +"%Y-%m-%d_%H-%M-%S").zip

    - name: list
      run: ls && echo "---" && ls cmake/build/

    - name: Upload Zip to Release (Windows)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release upload SNAPSHOT cmake/build/grpc-release-SNAPSHOT-*.zip

